apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: 00ehdcks/kub-demo-tasks:latest
          env:
            - name: AUTH_ADDRESS
              #value: '10.96.243.20'
              value: 'auth-service.default' #쿠버네티스의 내장 coreDNS기능 덕분에 가능하다
            - name: TASKS_FOLDER
              value: tasks
